### ISSUE TITLE
Integrate with WP API

### ISSUE THREAD

**Issue by pinkasey** [hijiriworld/intuitive-custom-post-order#13]
It would be very useful to have support for post order when getting posts with the [WP API](https://github.com/WP-API/WP-API/)
### Some technical details I've found along the way that I hope can help implement this issue:

I've found this code in WP API's [class-wp-rest-posts-controller.php](https://github.com/WP-API/WP-API/blob/cd2e15be0d8d29678af5c5c146741d03bf52a558/lib/endpoints/class-wp-rest-posts-controller.php), line 1636:
`
        if ( 'page' === $this->post_type || post_type_supports( $this->post_type, 'page-attributes' ) ) {
            $params['orderby']['enum'][] = 'menu_order';
        }
`

I'm not sure, but I think it means if all post-types support 'page-attributes', then menu_order would be supported by orderby.

So i think calline [add_post_type_support](https://codex.wordpress.org/Function_Reference/add_post_type_support)() somewhere, on all post type (all?), would do the trick.

**Comment by axelson** [comment]
As a work-around for this I am doing:

```
add_filter( "rest_<custom_post_type>_query", function( $args, $request )
{
  $args['orderby'] = 'menu_order';
  return $args;
}, 10, 2 );
```

So if you're filtering pages you should be able to use `rest_page_query`

Reference:
http://wordpress.stackexchange.com/a/225718/63153

**Comment by dianjuar** [comment]
I have a web site that has lessons and units, the units are taxonomies.

When I serve the taxonomies with the API this plugin works but I try to serve the lessons doesn't work
