### ISSUE TITLE
screen_icon is deprecated

### ISSUE THREAD

**Issue by nothingatalldotnet** [hijiriworld/intuitive-custom-post-order#24]
WP Admin shows the following:
> Notice: screen_icon is deprecated since version 3.8.0

settings.php needs a change on line 11
`<?php screen_icon( 'plugins' ); ?>`

https://developer.wordpress.org/reference/functions/screen_icon/

**Comment by austinpickett** [comment]
Looks like the fallback `get_screen_icon()` is deprecated too and Screen Icons are not used in WP 3.8+

**Comment by timohubois** [comment]
screen_icon function is not used anymore.
