### ISSUE TITLE
intuitive custom post order prevents yoast SEO plugin from saving meta description and title on a page, on multisite installations

### ISSUE THREAD

**Issue by macolo** [hijiriworld/intuitive-custom-post-order#25]
Reproduce:
- set up a multisite installation
- install the intuitive custom post order plugin and the yoast plugin
- set up a second site
- go to the second site, create a page and try to save the yoast meta description and/or title

**Comment by carstendietrich** [comment]
PR #22 solves this problem. This is open since September 2017, since then the author has not managed to fix the problem..

**Comment by cristianfx** [comment]
I'm having the same issue with intuitive custom post order.

**Comment by DarrenTheDev** [comment]
Issue seems to have been present since v3.1.0

**Comment by mbiang** [comment]
@hijiriworld is there any chance of getting PR #22 merged?

**Comment by timohubois** [comment]
Latest changes are merged into master. This should be part of the next release.
