### ISSUE TITLE
Yoast Plugin Conflict: Sorting breaks table display

### ISSUE THREAD

**Issue by hannahmwool** [hijiriworld/intuitive-custom-post-order#33]
Hi there,

Great plugin! 

I was experiencing an issue where the table breaks when re-ordering any custom post type or page.  tested all plugins and the culprit this is Yoast SEO Plugin. 

This is a same issue I found with another post type ordering plugin and let the know and they confirmed yoast interferes with it.

Thanks!

**Comment by Warface** [comment]
Seems that this plugin is dead, no fix since 2019 about that

**Comment by timohubois** [comment]
@hannahmwool and @Warface if you want, you can create PR at any time ✌️

**Comment by hannahmwool** [comment]
I think this was resolved. At least I've not noticed the issue for a long while.

**Comment by timohubois** [comment]
@hannahmwool thanks for your feedback! Then I will close the issue.
