### ISSUE TITLE
Problems in Multisite

### ISSUE THREAD

**Issue by idan-parallax** [hijiriworld/intuitive-custom-post-order#38]
hi
the function hicpo_get_blogs_of_user() creates a problem with multisite.
this is becuse the usage of switch_to_blog() function is done worng, on first change to main blog switch_to_blog() its ok but after this you need to do restore_current_blog() instead of switch_to_blog($current).
i got to this problem becuse it conflicted with yoast seo plugin, spesicly /wordpress-seo/admin/metabox/class-metabox.php file which checks:
if ( is_multisite() && ms_is_switched() ) {
    return false;
}
ms_is_switched() is looking for restore_current_blog() which clears the $GLOBALS['_wp_switched_stack']

thanks

**Comment by mvaneijgen** [comment]
Have you found a fix? Having the same issue at the moment.

**Comment by idan-parallax** [comment]
hi, yes just fix the problem in the function hicpo_get_blogs_of_user()
replace  switch_to_blog($current) with restore_current_blog()

**Comment by mvaneijgen** [comment]
@idan-parallax can you make a pull request?

**Comment by timohubois** [comment]
Related to #46, which is merged into master.
