### ISSUE TITLE
WordPress database error

### ISSUE THREAD

**Issue by julian-weinert** [hijiriworld/intuitive-custom-post-order#4]
This ALWAYS shows in my backend:

```
WordPress database error: [Unknown column 'term_order' in 'field list'] SELECT count(*) as cnt, max(term_order) as max, min(term_order) as min FROM wp_terms AS terms INNER JOIN wp_term_taxonomy AS term_taxonomy ON ( terms.term_id = term_taxonomy.term_id ) WHERE term_taxonomy.taxonomy = 'category'

Notice: Undefined offset: 0 in /wp-content/plugins/intuitive-custom-post-order/intuitive-custom-post-order.php on line 192

Notice: Trying to get property of non-object in /wp-content/plugins/intuitive-custom-post-order/intuitive-custom-post-order.php on line 192
```

**Comment by julian-weinert** [comment]
This is not an issue. The database user didn't have the correct permissions, so it couldn't alter the tables.

Nevertheless, I'd really like to get an MySQL error during installation / activation that tells me this issue. Now I was left with a non functioning installation.

**Comment by cedriccharles4** [comment]
Hello @julian-weinert ! 

I have the exact same notices. I don't understand in your comments how I can get rid of these notices ? Thank you in advance !
