### ISSUE TITLE
WordFence Flagged Critical Security Issue - Removed from WordPress

### ISSUE THREAD

**Issue by paragondigital** [hijiriworld/intuitive-custom-post-order#47]
Hello!

Is this plugin still being supported? We got a notification indicating that it's been removed from WordPress and just want to know if we should start looking for an alternative solution.

Thanks!

**Comment by micky-cormier** [comment]
Hi 
Got the same notification indicating that it's been removed from WordPress.
I didn't develop the website, have just taken over management of it,  and I'm not completely sure what this plugin actually does?

**Comment by paragondigital** [comment]
@micky-cormier The plugin basically changes the menu number of a page, post, custom post type, etc with some JavaScript peppered in to add fancy drop and drag functionality.

https://user-images.githubusercontent.com/81400287/213773125-c657d4c7-f759-40d8-87d0-d109fed8d2e7.mov

**Comment by diego-betto** [comment]
Same here, more than anything I would like to know if it has been removed because it is no longer maintained or for security problems.

**Comment by mackenzif** [comment]
@diego-betto It looks like a security issue, it was [flagged by our hosting](https://wpscan.com/plugin/intuitive-custom-post-order)

I am trying to figure out if ordering will revert or anything will be affected if uninstalled. I'm seeing that [Post Types Order](https://wordpress.org/plugins/post-types-order/) is a recommended alternative

**Comment by paragondigital** [comment]
@mackenzif From what we can see - nothing should be affected by by uninstalling. We're going to see if we can fix the security issue and submit a pull request for it. We're also actively reaching out to the current developer and seeing if he'd like to surrender ownership to us so maybe we can have this plugin back up and running and fully supported soon!
