### ISSUE TITLE
Vulnerabilities has discovered - SQL Injection

### ISSUE THREAD

**Issue by rajankarmakar** [hijiriworld/intuitive-custom-post-order#57]
Vulnerabilities have discovered that the currently installed version of the Intuitive Custom Post Order plugin has known security vulnerabilities. See [more](https://getshieldsecurity.com/tools/vulnerabilities-lookup/?type=plugin&slug=intuitive-custom-post-order&version=3.1.4.1).

**Comment by timohubois** [comment]
@rajankarmakar thanks for the feedback. Personaly, I think there is some exaggeration here. Of course it is possible to change things, but for this an administrative access is needed and if this is in the possession of someone else, the plugin itself is not the problem!

@hijiriworld have you found the time to take a deeper look into the [PR54](https://github.com/hijiriworld/intuitive-custom-post-order/pull/54). Would love to fix the security issues and use this PR as starting point.

**Comment by sajuahmed23** [comment]
@timohubois Can you say anything about the timing of the fix or if it will be fixed by the next release?

**Comment by timohubois** [comment]
Would really love to fix it and currently I’m waiting for feedback from @hijiriworld, to get a better starting point.

**Comment by timohubois** [comment]
#54 is merged. Will start to work on this asap.

**Comment by timohubois** [comment]
Created a branch with some changes: https://github.com/hijiriworld/intuitive-custom-post-order/pull/
