### ISSUE TITLE
[WordPress Plugin Directory] SECURITY Notice

### ISSUE THREAD

**Issue by hijiriworld** [hijiriworld/intuitive-custom-post-order#59]
The Reports

===========================
a clear and concise description of the issue: SQL injection vulnerability identified Jan 26, 2023 still has not been patched. It is still receiving hundreds of downloads a day, despite over 6 months since the vulnerability was identified. The plugin itself has not been updated in over 4 months, bringing up the question of whether it is abandonware.

- a link to the specific plugin - https://wordpress.org/plugins/intuitive-custom-post-order/
- whether or not you have validated the security issue yourself - I have not personally validated; I manage over 20+ sites that have this plugin installed and am taking proactive action.
- links to any public disclosures on 3rd party sites - https://patchstack.com/database/vulnerability/intuitive-custom-post-order/wordpress-intuitive-custom-post-order-plugin-3-1-3-authenticated-admin-sql-injection-vulnerability?_a_id=241

Previously:
The Intuitive Custom Post Order plugin for WordPress is vulnerable to authenticated settings change in versions up to and including 3.1.3 via the 'update-menu-order', 'update-menu-order-tags', and 'update-menu-order-sites' AJAX actions. This allows authenticated attackers with subscriber privileges or above, to change the order of tags in the tags menu.

Additionally it looks like the plugin may also be vulnerable to Authenticated (Admin+) SQL Injection in some circumstances as the 'update_options' function and 'refresh' function in the plugin both fail to use prepared statements and directly use the contents of the 'objects' and 'tags' parameters in database queries after they're saved to the 'hicpo_options' option. This is to some extent mitigated by the fact that the query is uses single quotes and by the addslashes() function used by WordPress on all incoming POST parameters but there are cases such as databases using the GBK character set where it may be possible to bypass the single quote being escaped, so it would probably be a best practice to prepare those statements.

**Comment by SteveRyan-ASU** [comment]
Hello. I've come here looking for an answer to this very question. We have received similar reports from other sources verifying this information. 

The issue describing the vulnerability was opened by the repository owner @hijiriworld. And so... I'm guessing that the issue is a known thing... but there may be an issue with applying the patch?

Can you please comment in a more meaningful way as to whether this project should be considered abandoned or if the patches are forthcoming? Thanks!

**Comment by lukasz-gorski** [comment]
Confirming that WPMU Defender Pro listing plugin as insecure. 

#Wordpress Intuitive Custom Post Order plugin <= 3.1.4.1 - Authenticated (Admin+) SQL Injection vulnerability
-Vulnerability type: SQL Injection
-No Update Available

Please consider the fix as high priority.

**Comment by level42ca** [comment]
Any updates on this? Is there a patch coming? Has this plugin been abandoned?

https://wpscan.com/plugin/intuitive-custom-post-order
https://wpscan.com/vulnerability/00ad48f2-c172-4418-b25b-9068f6af904f
https://www.wordfence.com/threat-intel/vulnerabilities/wordpress-plugins/intuitive-custom-post-order/intuitive-custom-post-order-313-authenticated-admin-sql-injection

@hijiriworld ? Any word?

**Comment by timohubois** [comment]
Will start to work on this asap.

**Comment by timohubois** [comment]
Created a branch with some changes: https://github.com/hijiriworld/intuitive-custom-post-order/pull/

**Comment by joeprongen** [comment]
Please tag latest merge, so it will be available for updating.

**Comment by angryaxi** [comment]
Please publish a new version of the plugin to the WordPress plugin directory so that sites can get this security fix.
