### ISSUE TITLE
SECURITY ISSUE

### ISSUE THREAD

**Issue by danfoley** [hijiriworld/intuitive-custom-post-order#62]
https://www.wordfence.com/threat-intel/vulnerabilities/wordpress-plugins/intuitive-custom-post-order/intuitive-custom-post-order-313-authenticated-admin-sql-injection

**Comment by timohubois** [comment]
@danfoley the current master branch includes the fixes and it only needs to deployed to the WordPress repository. This needs to be done by @hijiriworld and he wrote, that he will do this asap.
