### ISSUE TITLE
Changes aren't being saved when re-ordered

### ISSUE THREAD

**Issue by davegreyuk** [hijiriworld/intuitive-custom-post-order#65]
With 3.1.5 you can drag and reorder, but when the screen is refreshed the changes are not persisted.

Short example on a live site here: https://www.loom.com/share/a7414d03f9ea4559801e1787e95f6940

**Comment by timohubois** [comment]
@davegreyuk have you tried to deactivate and uninstall the plugin once and install it again?

**Comment by davegreyuk** [comment]
Yes. I get the same result, nothing is persisted.

On 2023-12-22 16:43, Timo Hubois wrote:

> @davegreyuk [1] have you tried to deactivate and uninstall the plugin 
> and install it again?
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/davegreyuk
[2] 
https://github.com/hijiriworld/intuitive-custom-post-order/issues/65#issuecomment-1867883196
[3]

**Comment by timohubois** [comment]
@davegreyuk tested it now on a local site. Registered a new Custom Post Type and a new Custom Taxonomy and it worked for the both (WordPress 6.4.2 and PHP 8.2). Have you also tested by disable all other plugins and with the current default theme?

**Comment by timohubois** [comment]
@davegreyuk can you check if this will fix the issue for you:
https://github.com/hijiriworld/intuitive-custom-post-order/tree/66-theres-a-duplication-of-the-word-hicpo-in-hicpo_load_script_css-capability-name

**Comment by davegreyuk** [comment]
I've downloaded a copy based on this branch and doesn't seem to have 
fixed the issue. I'll try and sort out a staging site to turn everything 
off in case its a plugin / theme issue.

On 2023-12-27 16:29, Timo Hubois wrote:

> @davegreyuk [1] can you check if this will fix the issue for you:
> https://github.com/hijiriworld/intuitive-custom-post-order/tree/66-theres-a-duplication-of-the-word-hicpo-in-hicpo_load_script_css-capability-name
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/davegreyuk
[2] 
https://github.com/hijiriworld/intuitive-custom-post-order/issues/65#issuecomment-1870455908
[3]

**Comment by davegreyuk** [comment]
Hi, I didn't think about server side caching and it looks like the Redis 
Object Cache plugin might be at fault. Turning that off it then worked 
on the staging site, so I'll try on their live site tonight to confirm.

Thanks for fixing the other issues so it no longer should show up as 
having a security risk.

Dave

On 2023-12-27 16:29, Timo Hubois wrote:

> @davegreyuk [1] can you check if this will fix the issue for you:
> https://github.com/hijiriworld/intuitive-custom-post-order/tree/66-theres-a-duplication-of-the-word-hicpo-in-hicpo_load_script_css-capability-name
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/davegreyuk
[2] 
https://github.com/hijiriworld/intuitive-custom-post-order/issues/65#issuecomment-1870455908
[3]

**Comment by timohubois** [comment]
@davegreyuk any updates from you? Can we close the issue?

**Comment by davegreyuk** [comment]
Sorry for being slow. Just checked on the production site with object 
cache turned off and it works correctly. This can be closed, thanks 
again for updating it for the other security issues.

On 2024-01-09 14:21, Timo Hubois wrote:

> @davegreyuk [1] any updates from you? Can we close the issue?
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you were mentioned.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/davegreyuk
[2] 
https://github.com/hijiriworld/intuitive-custom-post-order/issues/65#issuecomment-1883135953
[3]

**Comment by E-VANCE** [comment]
Also ran into this issue when using Redis / Object Caching. A quick workaround would be to utilize the "quick edit"-function and then _force save_ the term you have just sorted. Obviously not scalable but did it for me...
