### ISSUE TITLE
There's a duplication of the word "hicpo" in "hicpo_load_script_css" capability name.

### ISSUE THREAD

**Issue by mono-tong** [hijiriworld/intuitive-custom-post-order#66]
It appears there's a duplication of the word `hicpo` in `hicpo_load_script_css`,
which is causing the CSS and JS files not to load.

![image](https://github.com/hijiriworld/intuitive-custom-post-order/assets/8399702/03ff534f-d432-40cb-95df-2fc6ba031481)

![image](https://github.com/hijiriworld/intuitive-custom-post-order/assets/8399702/7e3390c6-d99b-4ab5-8a0e-0bc30c9a8896)

**Comment by timohubois** [comment]
@mono-tong many thanks for figure this out. Will update the code asap.

**Comment by timohubois** [comment]
@hijiriworld created a [branch](https://github.com/hijiriworld/intuitive-custom-post-order/tree/66-theres-a-duplication-of-the-word-hicpo-in-hicpo_load_script_css-capability-name) for this fix and think we should deploy this fix to the WordPress repo asap to prevent new open issues at the WordPress support forum and here on GitHub.  The issue should come up if the capability did not exist before. Maybe we should introduce automated tests to solve such kind of issues in the future.
